services:
  postgres:
    image: postgres:16
    container_name: carregador_pg
    environment:
      POSTGRES_USER: carregador
      POSTGRES_PASSWORD: carregador123
      POSTGRES_DB: carregador_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
